openapi: 3.0.3
info:
  title: Catflix Reviews Service
  description: Microservice de gestion des reviews pour le projet Catflix. Permet de créer, lire, modifier et supprimer des reviews, ainsi que de lister toutes les reviews d'un certain utilisateur ou d'une certaine vidéo, et de lister les 3 vidéos les mieux notées.
  version: 1.0.0
servers:
  - url: http://localhost:9003
    description: Development server
paths:

  /reviews/users/{pseudo}/videos/{hash}:
    parameters:
      - name: pseudo
        in: path
        required: true
        description: Pseudo de l'utilisateur
        schema:
          type: string
      - name: hash
        in: path
        required: true
        description: Hash de la vidéo
        schema:
          type: string

    post:
      summary: Créer une nouvelle review d'un utilisateur pour une vidéo
      requestBody:
        description: Données de la review à créer
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/review'
      responses:
        400:
          description: Le pseudo et/ou le hash en paramètre ne correspondent pas aux données de la review, ou aucun utilisateur n'existe pour ce pseudo, ou aucune vidéo n'existe pour ce hash, ou les données ne correspondent pas à ce qui serait attendu
        409:
          description: Une review existe déjà pour cet utilisateur et cette vidéo
        201:
          description: La review a été créée

    get:
      summary: Lire une review sur base d'un utilisateur et d'une vidéo
      responses:
        404:
          description: Aucune review n'a été trouvée pour cet utilisateur et cette vidéo
        200:
          description: Retourne la review de cet utilisateur pour cette vidéo
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/review'

    put:
      summary: Modifier une review sur base d'un utilisateur et d'une vidéo
      requestBody:
        description: Nouvelles données de la review
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/review'
      responses:
        400:
          description: Le pseudo et/ou le hash en paramètre ne correspondent pas aux données de la review, ou les données ne correspondent pas à ce qui serait attendu
        404:
          description: Aucune review n'a été trouvée pour cet utilisateur et cette vidéo
        200:
          description: La review a été modifiée

    delete:
      summary: Supprimer une review sur base d'un utilisateur et d'une vidéo
      responses:
        404:
          description: Aucune review n'a été trouvée pour cet utilisateur et cette vidéo
        200:
          description: La review a été supprimée

  /reviews/users/{pseudo}:
    parameters:
      - name: pseudo
        in: path
        required: true
        description: Pseudo de l'utilisateur
        schema:
          type: string

    get:
      summary: Lire les reviews d'un utilisateur
      responses:
        200:
          description: Retourne la liste de toutes les reviews de cet utilisateur
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/review'

    delete:
      summary: Supprimer les reviews d'un utilisateur
      responses:
        200:
          description: Toutes les reviews de cet utilisateur ont été supprimées

  /reviews/videos/{hash}:
    parameters:
      - name: hash
        in: path
        required: true
        description: Hash de la vidéo
        schema:
          type: string

    get:
      summary: Lire les reviews d'une vidéo
      responses:
        200:
          description: Retourne la liste de toutes les reviews de cette vidéo
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/review'

    delete:
      summary: Supprimer les reviews d'une vidéo
      responses:
        200:
          description: Toutes les reviews de cette vidéo ont été supprimées

  /reviews/best:
    get:
      summary: Lire les 3 vidéos les mieux notées
      responses:
        200:
          description: Retourne une liste ordonnée des 3 vidéos ayant les moyennes de note de reviews les plus élevées
          content:
            'application/json':
              schema:
                type: array
                maxItems: 3
                items:
                  $ref: '#/components/schemas/video'


components:
  schemas:
    review:
      type: object
      properties:
        pseudo:
          type: string
          description: Pseudo de l'utilisateur
        hash:
          type: string
          description: Hash de la vidéo
        rating:
          type: number
          description: Note de la review, entre 0 et 10
        comment:
          type: string
          description: Commentaire de la review
      example:
        pseudo: Cat4Life
        hash: dQw4w9WgXcQ
        rating: 10
        comment: Best video!
    video:
      type: object
      properties:
        hash:
          type: string
          description: Hash de la vidéo
        name:
          type: string
          description: Nom de la vidéo
        author:
          type: string
          description: Auteur de la vidéo
        creationYear:
          type: integer
          description: Année de création de la vidéo
        duration:
          type: integer
          description: Durée de la vidéo, en secondes
        url:
          type: string
          description: URL de la vidéo
      example:
        hash: dQw4w9WgXcQ
        name: Cutest kitty ever
        author: Cat4Life
        creationYear: 2009
        duration: 212
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ